---
title: "Relatório de Vendas Mensais"
output: html_document
date: "`r format(Sys.Date(), '%d/%m/%Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```


```{r importar_dados}
vendas <- read.csv("https://raw.githubusercontent.com/dayanebravo/LPA_R/refs/heads/main/aula_05/vendas.csv")
```

### Dados Resumidos
- O **total de vendas** em `r Sys.Date()` foi de R$ `r sum(vendas$valor * vendas$quantidade)`.
- **Produto mais vendido**: `r vendas$produto[which.max(vendas$quantidade)]`  
- **Média por região**:  

```{r media_regiao}
aggregate(valor ~ regiao, data = vendas, FUN = mean)
```

### Gráfico de Vendas por Categoria
```{r grafico_vendas}
library(ggplot2)
ggplot(vendas, aes(x = produto, y = valor * quantidade, fill = regiao)) +
  geom_bar(stat = "identity") +
  labs(title = "Vendas por Produto e Região", y = "Valor Total (R$)") +
  theme_minimal()
```

**Observações**:  
O relatório foi atualizado automaticamente em `r Sys.time()`.  